s = frozenset([1,2,3,4,5])
s1 = frozenset([5,4,6,7,8])
unio = s.union(s1)
inter = s.intersection(s1)
diff = s.difference(s1)
symediff = s.symmetric_difference(s1)
print(unio)
print(inter)
print(diff)
print(symediff)